name: lassa-env
channels:
  - conda-forge
dependencies:
  - python=3.9
  - numpy
  - pandas
  - scipy
  - matplotlib
  - xarray
  - netcdf4
  - scikit-learn
  - jupyter
  - pip
  - pip:
      - tqdm
      - pytest
      - ruff
      - black
